#!/bin/bash

exec /usr/bin/nodejs /opt/statsd/stats.js /opt/statsd/config.js >> /var/log/statsd.log 2>&1
exec /usr/bin/nodejs /opt/statsd/stats.js /opt/statsd/config2.js >> /var/log/statsd2.log 2>&1
exec /usr/bin/nodejs /opt/statsd/stats.js /opt/statsd/config3.js >> /var/log/statsd3.log 2>&1

